/**
 * Formatting Utilities
 * Helper functions for displaying data to users
 */

/**
 * Format MMR value with proper rounding
 */
export const formatMMR = (value) => {
  if (value === null || value === undefined) return 'N/A';
  return Math.round(value).toLocaleString();
};

/**
 * Format date/time for user display
 */
export const formatDate = (isoString) => {
  if (!isoString) return 'Never';

  const date = new Date(isoString);
  const now = new Date();
  const diffMs = now - date;
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  // Show relative time for recent dates
  if (diffDays === 0) return 'Today';
  if (diffDays === 1) return 'Yesterday';
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`;
  if (diffDays < 365) return `${Math.floor(diffDays / 30)} months ago`;

  // Show full date for older entries
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
};

/**
 * Format win rate as percentage
 */
export const formatWinRate = (rate) => {
  if (rate === null || rate === undefined) return 'N/A';
  return `${(rate * 100).toFixed(1)}%`;
};

/**
 * Format game duration
 */
export const formatDuration = (seconds) => {
  const minutes = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${minutes}:${secs.toString().padStart(2, '0')}`;
};

/**
 * Get race emoji/icon
 */
export const getRaceEmoji = (race) => {
  const raceMap = {
    Terran: '⚔️',
    Protoss: '🛡️',
    Zerg: '🦗',
    Random: '🎲'
  };
  return raceMap[race] || '❓';
};

/**
 * Get race color for styling
 */
export const getRaceColor = (race) => {
  const colorMap = {
    Terran: 'terran',
    Protoss: 'protoss',
    Zerg: 'zerg',
    Random: 'gray'
  };
  return colorMap[race] || 'gray';
};

/**
 * Get all races a player has played
 * Returns array of race objects with game counts
 */
export const getPlayerRaces = (player) => {
  const races = [];
  if (player.terran_games > 0) {
    races.push({ name: 'Terran', games: player.terran_games, emoji: '⚔️' });
  }
  if (player.protoss_games > 0) {
    races.push({ name: 'Protoss', games: player.protoss_games, emoji: '🛡️' });
  }
  if (player.zerg_games > 0) {
    races.push({ name: 'Zerg', games: player.zerg_games, emoji: '🦗' });
  }
  if (player.random_games > 0) {
    races.push({ name: 'Random', games: player.random_games, emoji: '🎲' });
  }

  // Sort by most played
  races.sort((a, b) => b.games - a.games);

  return races;
};

/**
 * Get MMR badge color based on value
 */
export const getMMRBadgeColor = (mmr) => {
  if (mmr >= 1300) return 'green';
  if (mmr >= 1200) return 'blue';
  if (mmr >= 1100) return 'yellow';
  return 'orange';
};

/**
 * Get fairness rating color
 */
export const getFairnessColor = (rating) => {
  const colorMap = {
    'Excellent': 'green',
    'Good': 'blue',
    'Fair': 'yellow',
    'Poor': 'orange',
    'Very Poor': 'red'
  };
  return colorMap[rating] || 'gray';
};

/**
 * Get player initials for avatar
 */
export const getInitials = (name) => {
  if (!name) return '?';
  const parts = name.trim().split(' ');
  if (parts.length === 1) {
    return parts[0].substring(0, 2).toUpperCase();
  }
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
};

/**
 * Generate team composition text for sharing
 */
export const generateTeamText = (teamSuggestion) => {
  const { team_1, team_2, win_probability_team_1, win_probability_team_2, fairness_rating } = teamSuggestion;

  let text = '🎮 SC2 Team Composition\n\n';

  text += `Team 1 (${(win_probability_team_1 * 100).toFixed(1)}% win probability)\n`;
  team_1.players.forEach(player => {
    text += `${getRaceEmoji(player.favorite_race || 'Random')} ${player.name} (${formatMMR(player.mmr)} MMR)\n`;
  });

  text += `\nTeam 2 (${(win_probability_team_2 * 100).toFixed(1)}% win probability)\n`;
  team_2.players.forEach(player => {
    text += `${getRaceEmoji(player.favorite_race || 'Random')} ${player.name} (${formatMMR(player.mmr)} MMR)\n`;
  });

  text += `\nBalance: ${fairness_rating}\n`;
  text += `\nGenerated by SC2 MMR Tracker`;

  return text;
};

/**
 * Copy text to clipboard
 */
export const copyToClipboard = async (text) => {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      document.body.appendChild(textArea);
      textArea.select();
      const success = document.execCommand('copy');
      document.body.removeChild(textArea);
      return success;
    }
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
};

/**
 * Parse API error message
 */
export const parseErrorMessage = (error) => {
  if (error.userMessage) {
    return error.userMessage;
  }

  if (error.response?.data?.detail) {
    const detail = error.response.data.detail;

    // Check for Winner Determination errors FIRST (before Parse error check)
    // Backend sends: "Winner determination failed: {message}"
    if (detail.startsWith('Winner determination failed:')) {
      // Return the full message from backend - it contains detailed diagnostics
      return detail.replace('Winner determination failed: ', 'Winner determination failed: ');
    }

    // Then check for Parse errors
    // Backend sends: "Parse error: {message}"
    if (detail.startsWith('Parse error:')) {
      return detail; // Return full backend message
    }

    // Translate other common backend errors to friendly messages
    if (detail.includes('Validation failed')) {
      return detail.replace('Validation failed: ', '');
    }
    if (detail.includes('Invalid game mode') || detail.includes('Invalid number of players')) {
      return "This game mode isn't supported (only 2v2, 3v3, 4v4, 5v5)";
    }
    if (detail.includes('Game too short') || detail.includes('duration')) {
      return 'This game was too short to analyze (under 3 minutes)';
    }
    if (detail.includes('Missing players')) {
      return "Couldn't identify all players in this match";
    }

    return detail;
  }

  return 'An unexpected error occurred';
};
